# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.9

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /autofs/nccs-svm1_sw/titan/.swci/0-login/opt/spack/20170612/linux-suse_linux11-x86_64/gcc-4.3.4/cmake-3.9.0-owxiriblogovogl5zbrg45ulm3ln34cx/bin/cmake

# The command to remove a file.
RM = /autofs/nccs-svm1_sw/titan/.swci/0-login/opt/spack/20170612/linux-suse_linux11-x86_64/gcc-4.3.4/cmake-3.9.0-owxiriblogovogl5zbrg45ulm3ln34cx/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /ccs/home/tneuroth/xgc-summarizer

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /ccs/home/tneuroth/xgc-summarizer

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/autofs/nccs-svm1_sw/titan/.swci/0-login/opt/spack/20170612/linux-suse_linux11-x86_64/gcc-4.3.4/cmake-3.9.0-owxiriblogovogl5zbrg45ulm3ln34cx/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/autofs/nccs-svm1_sw/titan/.swci/0-login/opt/spack/20170612/linux-suse_linux11-x86_64/gcc-4.3.4/cmake-3.9.0-owxiriblogovogl5zbrg45ulm3ln34cx/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /ccs/home/tneuroth/xgc-summarizer/CMakeFiles /ccs/home/tneuroth/xgc-summarizer/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /ccs/home/tneuroth/xgc-summarizer/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named kdtree

# Build rule for target.
kdtree: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 kdtree
.PHONY : kdtree

# fast build rule for target.
kdtree/fast:
	$(MAKE) -f CMakeFiles/kdtree.dir/build.make CMakeFiles/kdtree.dir/build
.PHONY : kdtree/fast

#=============================================================================
# Target rules for targets named summarizer

# Build rule for target.
summarizer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 summarizer
.PHONY : summarizer

# fast build rule for target.
summarizer/fast:
	$(MAKE) -f CMakeFiles/summarizer.dir/build.make CMakeFiles/summarizer.dir/build
.PHONY : summarizer/fast

#=============================================================================
# Target rules for targets named kdtree-cu

# Build rule for target.
kdtree-cu: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 kdtree-cu
.PHONY : kdtree-cu

# fast build rule for target.
kdtree-cu/fast:
	$(MAKE) -f CMakeFiles/kdtree-cu.dir/build.make CMakeFiles/kdtree-cu.dir/build
.PHONY : kdtree-cu/fast

source/SummarizerMPIAdios1VTKmInterpolation.o: source/SummarizerMPIAdios1VTKmInterpolation.cpp.o

.PHONY : source/SummarizerMPIAdios1VTKmInterpolation.o

# target to build an object file
source/SummarizerMPIAdios1VTKmInterpolation.cpp.o:
	$(MAKE) -f CMakeFiles/summarizer.dir/build.make CMakeFiles/summarizer.dir/source/SummarizerMPIAdios1VTKmInterpolation.cpp.o
.PHONY : source/SummarizerMPIAdios1VTKmInterpolation.cpp.o

source/SummarizerMPIAdios1VTKmInterpolation.i: source/SummarizerMPIAdios1VTKmInterpolation.cpp.i

.PHONY : source/SummarizerMPIAdios1VTKmInterpolation.i

# target to preprocess a source file
source/SummarizerMPIAdios1VTKmInterpolation.cpp.i:
	$(MAKE) -f CMakeFiles/summarizer.dir/build.make CMakeFiles/summarizer.dir/source/SummarizerMPIAdios1VTKmInterpolation.cpp.i
.PHONY : source/SummarizerMPIAdios1VTKmInterpolation.cpp.i

source/SummarizerMPIAdios1VTKmInterpolation.s: source/SummarizerMPIAdios1VTKmInterpolation.cpp.s

.PHONY : source/SummarizerMPIAdios1VTKmInterpolation.s

# target to generate assembly for a file
source/SummarizerMPIAdios1VTKmInterpolation.cpp.s:
	$(MAKE) -f CMakeFiles/summarizer.dir/build.make CMakeFiles/summarizer.dir/source/SummarizerMPIAdios1VTKmInterpolation.cpp.s
.PHONY : source/SummarizerMPIAdios1VTKmInterpolation.cpp.s

source/kdtree/ParticleMeshInterpolator2D.o: source/kdtree/ParticleMeshInterpolator2D.cpp.o

.PHONY : source/kdtree/ParticleMeshInterpolator2D.o

# target to build an object file
source/kdtree/ParticleMeshInterpolator2D.cpp.o:
	$(MAKE) -f CMakeFiles/kdtree.dir/build.make CMakeFiles/kdtree.dir/source/kdtree/ParticleMeshInterpolator2D.cpp.o
.PHONY : source/kdtree/ParticleMeshInterpolator2D.cpp.o

source/kdtree/ParticleMeshInterpolator2D.i: source/kdtree/ParticleMeshInterpolator2D.cpp.i

.PHONY : source/kdtree/ParticleMeshInterpolator2D.i

# target to preprocess a source file
source/kdtree/ParticleMeshInterpolator2D.cpp.i:
	$(MAKE) -f CMakeFiles/kdtree.dir/build.make CMakeFiles/kdtree.dir/source/kdtree/ParticleMeshInterpolator2D.cpp.i
.PHONY : source/kdtree/ParticleMeshInterpolator2D.cpp.i

source/kdtree/ParticleMeshInterpolator2D.s: source/kdtree/ParticleMeshInterpolator2D.cpp.s

.PHONY : source/kdtree/ParticleMeshInterpolator2D.s

# target to generate assembly for a file
source/kdtree/ParticleMeshInterpolator2D.cpp.s:
	$(MAKE) -f CMakeFiles/kdtree.dir/build.make CMakeFiles/kdtree.dir/source/kdtree/ParticleMeshInterpolator2D.cpp.s
.PHONY : source/kdtree/ParticleMeshInterpolator2D.cpp.s

source/kdtree/ParticleMeshInterpolator2D.o: source/kdtree/ParticleMeshInterpolator2D.cu.o

.PHONY : source/kdtree/ParticleMeshInterpolator2D.o

# target to build an object file
source/kdtree/ParticleMeshInterpolator2D.cu.o:
	$(MAKE) -f CMakeFiles/kdtree-cu.dir/build.make CMakeFiles/kdtree-cu.dir/source/kdtree/ParticleMeshInterpolator2D.cu.o
.PHONY : source/kdtree/ParticleMeshInterpolator2D.cu.o

source/kdtree/ParticleMeshInterpolator2D.i: source/kdtree/ParticleMeshInterpolator2D.cu.i

.PHONY : source/kdtree/ParticleMeshInterpolator2D.i

# target to preprocess a source file
source/kdtree/ParticleMeshInterpolator2D.cu.i:
	$(MAKE) -f CMakeFiles/kdtree-cu.dir/build.make CMakeFiles/kdtree-cu.dir/source/kdtree/ParticleMeshInterpolator2D.cu.i
.PHONY : source/kdtree/ParticleMeshInterpolator2D.cu.i

source/kdtree/ParticleMeshInterpolator2D.s: source/kdtree/ParticleMeshInterpolator2D.cu.s

.PHONY : source/kdtree/ParticleMeshInterpolator2D.s

# target to generate assembly for a file
source/kdtree/ParticleMeshInterpolator2D.cu.s:
	$(MAKE) -f CMakeFiles/kdtree-cu.dir/build.make CMakeFiles/kdtree-cu.dir/source/kdtree/ParticleMeshInterpolator2D.cu.s
.PHONY : source/kdtree/ParticleMeshInterpolator2D.cu.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... kdtree"
	@echo "... summarizer"
	@echo "... kdtree-cu"
	@echo "... source/SummarizerMPIAdios1VTKmInterpolation.o"
	@echo "... source/SummarizerMPIAdios1VTKmInterpolation.i"
	@echo "... source/SummarizerMPIAdios1VTKmInterpolation.s"
	@echo "... source/kdtree/ParticleMeshInterpolator2D.o"
	@echo "... source/kdtree/ParticleMeshInterpolator2D.i"
	@echo "... source/kdtree/ParticleMeshInterpolator2D.s"
	@echo "... source/kdtree/ParticleMeshInterpolator2D.o"
	@echo "... source/kdtree/ParticleMeshInterpolator2D.i"
	@echo "... source/kdtree/ParticleMeshInterpolator2D.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

